In [1]:
import torch
from torch.utils.data import Dataset
import torch.nn.functional as F
import torch.nn as nn
import numpy as np

In [2]:
x = []
y = []
for i in range(5):
    x.append([float(i),float(i+1)])
    y.append(0)
x = x*50
y = y*50
x1 = []
y1 = []
for i in range(1,6):
    x1.append([float(i),float(i-1)])
    y1.append(1)
x1 = x1*50
y1 = y1*50
x = x1+x
y = y1+y
print(len(x))

print(len(y))


500
500


In [7]:
x = np.array(x,dtype=float)
y = np.array(y,dtype=float)
x = torch.from_numpy(x)
y = torch.from_numpy(y)
x.dtype
x

tensor([[1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.],
        [5., 4.],
        [1

In [8]:
N, D_in, H1, H2, D_out = 10, 2, 30, 15, 1
dtype = torch.float64
device = torch.device("cpu")
lr = .01
epochs = 1

In [9]:
w1 = torch.randn(D_in, H1, device=device, dtype=dtype, requires_grad=True)
#b1 = torch.randn(D, H1, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H1, H2, device=device, dtype=dtype, requires_grad=True)
w3 = torch.randn(H2, D_out, device=device, dtype=dtype, requires_grad=True)
w1.dtype
#print(w1)

torch.float64

In [12]:
'''print(x.shape)
print(w1.shape)
print(w2.shape)
print(w3.shape)
print(y.shape)'''

'''for i,j in zip(x,y):
    print (i ,j)'''


'for i,j in zip(x,y):\n    print (i ,j)'

In [32]:
for epoch in range(1000):
    # forward pass
    runningLoss = 0
    yhat = F.relu(F.relu(x.mm(w1)).mm(w2)).mm(w3)
    #print(yhat.shape)
    #print(y.shape)
    loss = (yhat - y).pow(2).sum()
    runningLoss += loss.item()
    loss.backward()
    #print(w1)
    with torch.no_grad():
        w1 -= lr *w1.grad
        w2 -= lr *w2.grad
        w3 -= lr *w3.grad
        w1.grad.zero_()
        w2.grad.zero_()
        
print(w1)

tensor([[ -4.2569e-01,  -3.7438e-01,  -3.4843e+05,  -2.5139e+32,  -2.1634e+00,
          -1.3821e+33,  -1.3208e+00,  -6.5026e+32,  -2.2259e+04,  -2.7389e+32,
          -5.7900e+05,  -3.3335e+04,  -1.1259e+32,  -5.6767e+04,  -1.0843e+31,
          -1.4955e+04,  -3.0923e+32,  -9.3056e-01,  -1.9561e+05,  -1.3316e+00,
         -1.8659e+163,  -5.8930e+04, -6.6451e+164,  -9.4344e+03,  -1.3568e+04,
          -1.3809e+00,  -4.9164e+32,  -3.2026e+05,  -2.3771e+05,  -1.4403e+00],
        [ -2.5439e-01,  -6.6599e+03,  -2.6138e+05,  -2.4913e+32,  -3.5853e-01,
          -1.3697e+33,  -7.6413e-01,  -6.4439e+32,  -1.2133e+00,  -2.7141e+32,
          -3.8832e+05,  -2.8405e+04,  -1.1158e+32,  -2.2055e+04,  -1.0689e+31,
          -2.0272e+00,  -2.2733e+32,  -5.0332e-01,  -1.2838e+05,  -1.8944e+00,
         -1.8653e+163,  -2.7630e+00, -6.6433e+164,  -6.5910e+03,  -2.9058e+04,
          -1.4408e+00,  -4.8721e+32,  -2.1627e+05,  -1.9177e+05,  -5.0060e-01]],
       dtype=torch.float64, requires_grad=True)


In [34]:
k= torch.tensor([[1,0]],dtype=dtype)
ypred = k.mm(w1).clamp(min=0).mm(w2).clamp(min=0).mm(w3)
ypred

tensor([[0.]], dtype=torch.float64, grad_fn=<MmBackward>)