# Linear Regression 1D: Prediction

In [1]:
import torch

### Prediction
Let us create the following expressions:

𝑏=−1,𝑤=2 

𝑦̂ =−1+2𝑥

In [2]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)
print(w,'\n',b)

tensor(2., requires_grad=True) 
 tensor(-1., requires_grad=True)


In [3]:
def forward(x):
    yhat = w*x + b
    return yhat

In [6]:
#prediction at x=1
x = torch.tensor([[1.0]])
yhat = forward(x)
print(yhat)

tensor([[1.]], grad_fn=<AddBackward0>)


In [9]:
# multiple inputs of x
x1 = torch.tensor([[1.0], [2.0]])
print(x1.shape)
yhat1 = forward(x1)
print(yhat1)

torch.Size([2, 1])
tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


### Class Linear

The linear class can be used to make a prediction. We can also use the linear class to build more complex models. 

In [10]:
from torch.nn import Linear

In [11]:
torch.manual_seed(1)

In [12]:
# linear regression model
lr = Linear(in_features=1, out_features=1, bias=True)
print(list(lr.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [14]:
print(lr.state_dict())
# returns a python dict object corresponding to the layers of each parameter tensor
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [16]:
print(lr.weight)
print(lr.bias)

Parameter containing:
tensor([[0.5153]], requires_grad=True)
Parameter containing:
tensor([-0.4414], requires_grad=True)


In [17]:
# making the prediction at x = 1
x  = torch.tensor([[1.0]])
yhat = lr(x)
print(yhat)

tensor([[0.0739]], grad_fn=<AddmmBackward>)


In [18]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)#like doing the forward function
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)


### Building Custom Module
make more complex models using this method

In [19]:
from torch import nn

In [21]:
class LR(nn.Module):
    
    def __init__(self, input_size, output_size):
        #intherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        out = self.linear(x)
        return out

In [24]:
lr = LR(1,1)
print(list(lr.parameters()))
print(lr.linear)

[Parameter containing:
tensor([[-0.2057]], requires_grad=True), Parameter containing:
tensor([0.5087], requires_grad=True)]
Linear(in_features=1, out_features=1, bias=True)


In [25]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.3030]], grad_fn=<AddmmBackward>)


In [26]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.3030],
        [0.0973]], grad_fn=<AddmmBackward>)


In [27]:
print("Python dictionary: ", lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[-0.2057]])), ('linear.bias', tensor([0.5087]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.2057]]), tensor([0.5087])])
