## Optimizer

In [2]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from torch import nn, optim
import matplotlib.pyplot as plt

### Steps
1) create a Dataset object<br>
2) create a custom module- using nn.module<br>
3) create a criterion(loss function)--can get it from nn<br>
4) create a dataloader object<br>
5) create a model<br>
6) create an optimizer object<br>
7) write the training code<br>


In [3]:
torch.manual_seed(1)
X = torch.arange(-3,3,0.1).view(-1,1)
f = -3 * X + 1
Y = f + 0.1 * torch.randn(X.size())

In [ ]:
class DatasetSLR(Dataset):
    
    def __init__(self,x,y, transform=None):
        self.len = x.shape[0]
        self.x = x
        self.y = y
        self.transform = transform
        
    def __getitem__ (self,index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

print(X.shape)
print(Y)

datasetLR = DatasetSLR(X,Y)
print(datasetLR[0])
print(datasetLR[1:3])
print('\n the size is',len(datasetLR))

In [5]:
class LR(nn.Module):
    
    def __init__(self,input_size,output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size,output_size)
        
    def forward(self,x):
        out = self.linear(x)
        return out

model = LR(1,1)
print(model)
print(list(model.parameters()))
print(model.linear)
print(model.state_dict())
begW = (model.linear.weight)
print('\n the beginning weight is ', begW)
bedB = model.linear.bias
print('\nthe beginning bias is ', bedB)

LR(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
[Parameter containing:
tensor([[0.3636]], requires_grad=True), Parameter containing:
tensor([0.4957], requires_grad=True)]
Linear(in_features=1, out_features=1, bias=True)
OrderedDict([('linear.weight', tensor([[0.3636]])), ('linear.bias', tensor([0.4957]))])

 the beginning weight is  Parameter containing:
tensor([[0.3636]], requires_grad=True)

the beginning bias is  Parameter containing:
tensor([0.4957], requires_grad=True)


In [6]:
criterion = nn.MSELoss()
trainloader = DataLoader(dataset=datasetLR, batch_size=1)
optimizer = optim.SGD(model.parameters(), lr=0.01)
#model = LR(1,1)
#print(model)
#print(list(model.parameters()))
#print(model.linear)
#print(model.state_dict())

In [ ]:
def train1(model,trainloader,epochsNum):
    train_loss = []
    for epoch in range(epochsNum):
        runningloss = 0.0
        for x,y in trainloader:
            yhat = model(x)
            loss = criterion(yhat,y)
            #print(model.linear.weight.grad)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            runningloss+=loss.item()
        loss = runningloss/float(len(trainloader))
        #print(runningloss)
        train_loss.append(loss)
        print('Epoch {} of {}, Train Loss: {:.3f}'.format(
                epoch+1, epochsNum, loss))
    return train_loss

loss1 = train1(model,trainloader,10)

In [ ]:
plt.plot(loss1,label = "bs=1")
plt.plot(loss2,label = "bs=12")
plt.xlabel('epoch')
plt.ylabel('Cost/ total loss')
plt.legend()
plt.show()